[project]
authors = ["Brian Mc Donald <brian@brianmcdonald.me>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "access"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
osmnx = ">=2.0.1,<3"
polars = ">=1.21.0,<2"
ipykernel = ">=6.29.5,<7"
networkx = ">=3.4.2,<4"
matplotlib = ">=3.10.0,<4"
shapely = ">=2.0.6,<3"
fastexcel = ">=0.12.1,<0.13"
requests = ">=2.32.3,<3"
coreapi-cli = ">=1.0.9,<2"
openpyxl = ">=3.1.5,<4"
pyyaml = ">=6.0.2,<7"
nbformat = ">=5.10.4,<6"
nbclient = ">=0.10.2,<0.11"
folium = ">=0.19.4,<0.20"
seaborn = ">=0.13.2,<0.14"
