project:
  type: manuscript
  output-dir: '../docs/'
  render:
    - index.qmd


manuscript:
  article: index.qmd
  # resources:
  #   - '../data/external/healthsites.geojson'
  # notebooks:
      # - notebook: ../notebooks/processing.ipynb
      #   title: Data Processing
      # - notebook: ../notebooks/vis.ipynb
      #   title: Visualization

format:
  html:
    toc: true
    theme:
       - cosmo
    comments:
      hypothesis: false
    # title-block-banner: '#0035a0'
    # output-file: new
    lightbox: true
    embed-resources: true
    number-sections: true
    fig-cap-location: margin
  typst: default
  # epub: default
  # ipynb: default
  # revealjs: 
  #   output-file: presentation.html
  # revealjs: default

format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf
  # epub: default

# other-links:
#       - text: IOM
#         href: https://iom.int/



